### ISSUE TITLE
help

### ISSUE THREAD

**Issue by PZiZiZi** [lazyVinh/iram#1]
I'm sorry to bother you. I really want to know which paper proposed the method you used to  conserve orthogonality in file 'Arnoldi.m' and I want to read it. Thank you!

**Comment by PZiZiZi** [comment]
Is it modified Gram-Schmidt method?

**Comment by LazyVinh** [comment]
Hi @PZiZiZi,

unfortunately, I forgot where I got this from. The idea is not hard to explain, though:

You have orthonormal vectors V := [v_1, ..., v_k] and the vector f is _almost_ orthogonal to those, i.e. V' * f = c where c is almost the k-zero-vector.

Then the vector f - V * c is _exactly_ orthogonal to V.

If you need something to cite, maybe [Wikipedia](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process#Numerical_stability) can help.
